version: '2'

services:
  web:
    restart: always
    image: {{cookiecutter.project_slug}}_web
    build: ./web/
    # Expose ports without publishing them
    expose:
      - "8000"
    links:
      - db:db
    env_file: .env
    volumes:
      - web_public_prod:/public:rw
    depends_on:
      - db
    command: /run_server.sh gunicorn

  nginx:
    restart: always
    image: {{cookiecutter.project_slug}}_nginx
    build: ./nginx/
    # Expose ports and publish them to the host machine
    ports:
      - "80:80"
    volumes:
      - web_public_prod:/public:rw
    links:
      - web:web
    depends_on:
      - web

  db:
    restart: always
    image: {{cookiecutter.project_slug}}_db
    build: ./db/
    env_file: .env
    volumes:
      - db_data_prod:/var/lib/postgresql/data:rw
      - db_backup_prod:/backups
      - web_public_prod:/public:rw
    # Expose ports without publishing them
    expose:
      - "5432"

volumes:
  db_data_prod:
    driver: local
  db_backup_prod:
    driver: local
  web_public_prod:
    driver: local
